[package]
name = "bifrost-sdp"
version = "0.1.0"
authors = ["Zizheng Tai <me@zizheng.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
