name: Rust

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1

    // Only lint on Linux as code style isn't platform-dependent
    - name: Lint
      if: matrix.os == 'ubuntu-latest'
      run: |
        rustup component add rustfmt clippy
        cargo fmt --all -- --check
        cargo clippy --all-targets --all-features --all -- -D warnings

    - name: Test
      run: cargo test --all-features --all-targets --all

  // Audit in a separate job because installing cargo-audit takes a long time
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Audit dependencies
      run: |
        cargo install cargo-audit
        cargo generate-lockfile
        cargo audit
