name: Rust

on: [push, pull_request]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    
    # macOS doesn't come with Rust installed
    - name: Install
      if: startsWith(matrix.os, 'macOS')
      run: curl -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain none

    # Only lint on Linux as code style isn't platform-dependent
    - name: Lint
      if: matrix.os == 'ubuntu-latest'
      run: |
        rustup component add rustfmt clippy
        cargo fmt --all -- --check
        cargo clippy --all-targets --all-features --all -- -D warnings

    - name: Test (Linux & Windows)
      if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'windows')
      run: cargo test --all-targets --all-features --all

    # We installed Rust manually on macOS, so need to configure the environment
    - name: Test (macOS)
      if: startsWith(matrix.os, 'macOS')
      run: |
        source $HOME/.cargo/env
        cargo test --all-targets --all-features --all

  # Audit in a separate job because installing cargo-audit takes a long time
  audit:
    name: Audit dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: cargo install cargo-audit
    - name: Audit
      run: |
        cargo generate-lockfile
        cargo audit
        
