name: Rust

on: [push, pull_request]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    
    # macOS doesn't come with Rust installed
    - name: Install
      if: matrix.os == 'macOS-latest'
      run: curl -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain none

    # Only lint on Linux as code style isn't platform-dependent
    - name: Lint
      if: matrix.os == 'ubuntu-latest'
      run: |
        rustup component add rustfmt clippy
        cargo fmt --all -- --check
        cargo clippy --all-targets --all-features --all -- -D warnings

    - name: Test
      env:
        PATH: $HOME/.cargo/bin:$PATH
      run: echo $PATH

  # Audit in a separate job because installing cargo-audit takes a long time
  audit:
    name: Audit dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: cargo install cargo-audit
    - name: Audit
      run: |
        cargo generate-lockfile
        cargo audit
        
